# Pull the profiling metric from brili -p output
extract = 'total_dyn_inst:\s+(\d+)'

benchmarks = '../../bril/benchmarks/**/*.bril'


timeout = 10
forbid_missing = true   # <--- Add this to forbid missing metrics

[runs.baseline]
# Golden run: no optimization, just interpret with profiling.
pipeline = [
  "bril2json",
  "brili -p",
]


[runs.tdce]
pipeline = [
  "bril2json",
  "python3 tdce.py",
  "brili -p",
]

[runs.lvn]
pipeline = [
  "bril2json",
  "python3 lvn.py",
  "brili -p",
]
